apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260608-224623-qohh0mmi0ztp-service
spec:
  selector:
    app: enterprise-system-20260608-224623-qohh0mmi0ztp
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
